### ISSUE TITLE
Suggestion for variable renaming

### ISSUE THREAD

**Issue by howellevans** [Azure/azure-spring-cloud-reference-architecture#103]
I used this to reference how to build Azure Spring Cloud through Terraform. It was very helpful. I would however suggest some variable name changes. The variables imply it should be a route id which doesn't exist instead of the route table id. which does exist.

sc_default_apps_route ---> sc_default_apps_route_table_id
sc_default_runtime_route ---> sc_default_runtime_route_table_id

https://github.com/Azure/azure-spring-cloud-reference-architecture/blob/8d735cce1a774d928739c09d42af014062369e9f/terraform/modules/azure_spring_cloud/variables.tf#L18
https://github.com/Azure/azure-spring-cloud-reference-architecture/blob/8d735cce1a774d928739c09d42af014062369e9f/terraform/modules/azure_spring_cloud/variables.tf#L18

**Comment by kriation** [comment]
Fixed as of #131
