### ISSUE TITLE
Provision jumpbox with Microsoft Edge

### ISSUE THREAD

**Issue by hemantmalik** [Azure/azure-spring-cloud-reference-architecture#112]
az login step when running the powershell leads to the need for signing in using browser. The default experience with IE is painful. After a lot of clicks to allow it to open the link it finally results in the below error 
![image](https://user-images.githubusercontent.com/26748353/130133558-2196d9d3-c488-4985-9eba-daa8e4a51e98.png)

**Comment by kriation** [comment]
Fixed as of #130
