### ISSUE TITLE
Use Windows Client for Jumphost

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-spring-cloud-reference-architecture#42]

**Comment by dapolloxp** [comment]
This is completed for Terraform, however, it requires a server OS per @aultt

**Comment by selvasingh** [comment]
@dapolloxp and @aultt - sounds good. May I request you add PostgreSQL CLI and SQLCMD CLI as well?

**Comment by dapolloxp** [comment]
> @dapolloxp and @aultt - sounds good. May I request you add PostgreSQL CLI and SQLCMD CLI as well?

If it’s on chocolately, it should be easy enough.

**Comment by aultt** [comment]
> > @dapolloxp and @aultt - sounds good. May I request you add PostgreSQL CLI and SQLCMD CLI as well?
> 
> If it’s on chocolately, it should be easy enough.

@dapolloxp  and @selvasingh both are on chocolatey so easy add.

**Comment by aultt** [comment]
pushed changes requested
