### ISSUE TITLE
Should help users with list of regions that support Azure Spring Cloud

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-spring-cloud-reference-architecture#65]
The following query will share the general list of available regions but not scoped to regions where Azure Spring Cloud is supported

![image](https://user-images.githubusercontent.com/3642444/106365435-8220f780-62ea-11eb-8b3b-89686834e5f8.png)

The following query will supply the list of regions that support Azure Spring Cloud
`https://azure.microsoft.com/global-infrastructure/services/?products=spring-cloud&regions=all`

**Comment by djr1991** [comment]
updated CLI README to include this query
