### ISSUE TITLE
Explain what are the input values for terraforming the app gateway

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-spring-cloud-reference-architecture#69]
![image](https://user-images.githubusercontent.com/3642444/106367037-c1544600-62f4-11eb-9b25-bcf88a05ef3b.png)

We should explain where to get the app FQDN and self-signed certificate (create KV and get self-signed should be okay?)

**Comment by ryhud** [comment]
This has been updated with descriptions for the variables
